name: 'Build Ghost Theme'
author: 'Douglas Beal <git@dougbeal.com>'
description: 'Build a Ghost Theme to a .zip filename based on version pulled from package.json'
outputs:
  release_file:
    description: 'theme zip filename'
  release_name:
    description: 'theme filename sans extension'
  release_tag:
    description: 'theme release tag'
runs:    
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon:  'folder'
  color: 'purple'
